// Copyright (c) 2026 Witalis Domitrz <witekdomitrz@gmail.com>
// AGPL License

//! The shared core's native front end: one CLI, no server.
//!
//! Everything the studio does happens in the browser, in wasm. This binary
//! exists to convert a picture to a mosaic from the same public library the
//! browser uses, and for nothing else — publishing the studio is `cargo
//! build`'s job, not a subcommand (see `build.rs`).

mod cli;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();

    // There is no default action. The studio is generated by the build, and a
    // bare invocation used to start a long-running file server, which made the
    // binary look like a service when it is a tool.
    if args.is_empty() || args[0] == "--help" || args[0] == "-h" {
        println!("{}", cli::help());
        if args.is_empty() {
            std::process::exit(2);
        }
        return;
    }

    let result = cli::run(&args[1..]);
    if let Err(error) = result {
        eprintln!("lego-mosaic: {error}");
        std::process::exit(2);
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn a_bare_invocation_asks_for_a_command_rather_than_serving() {
        // The host is gone, so the help must not offer it.
        let help = super::cli::help();
        assert!(
            !help.contains("serve"),
            "help still advertises a server:\n{help}"
        );
        assert!(help.contains("convert"), "help should describe convert");
    }

    #[test]
    fn help_does_not_promise_a_run_step_for_the_static_site() {
        let help = super::cli::help();
        assert!(
            !help.contains("dist"),
            "the site is generated by the build, not a subcommand:\n{help}"
        );
    }
}
