// Copyright (c) 2026 Witalis Domitrz <witekdomitrz@gmail.com>
// AGPL License

//! The shared core's native front end: one CLI, no server.
//!
//! Everything the studio does happens in the browser, in wasm. This binary
//! exists to convert a picture to a mosaic from the same public library the
//! browser uses, and for nothing else — publishing the studio is `cargo
//! build`'s job, not a subcommand (see `build.rs`).

mod cli;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();

    // There is no default action: the studio is generated by the build, and a
    // bare invocation used to start a long-running file server, which made a
    // conversion tool look like a service.
    if args.is_empty() || args[0] == "--help" || args[0] == "-h" {
        println!("{}", cli::help());
        if args.is_empty() {
            std::process::exit(2);
        }
        return;
    }

    let result = cli::run(&args[1..]);
    if let Err(error) = result {
        eprintln!("lego-mosaic: {error}");
        std::process::exit(2);
    }
}
